CHANGELOG.md, package.json, src/index.ts, src/poller.ts
---
---
The `init` method is only meant to be called once during the application lifecycle. If the developer calls it twice in a row, that should not create duplicate polling processes; the second call should stop the polling of the previous call.
If the init method is called a second time, stop the polling process from the previous call before re-initializing the poller.
In a demo app, called the `init` method 3 times in a row. Wait 5 minutes. Verify the client only polls once after the 5 minute poll interval.
[//]: # …
=> Release client resources if it is initialized twice

CHANGELOG.md, package.json, src/configuration-store.spec.ts, src/configuration-store.ts, src/constants.ts, src/index.ts, yarn.lock
---
---
See discussion in this thread: https://github.com/Eppo-exp/python-sdk/pull/3#discussion_r866301635
The advantage of using an LRU cache instead of a TTL cache is that it allows the SDK to continue serving stale results for some time after a fatal error in the polling process. Although, the cache will still get cleared if there is a deployment.
Swapped the node-cache library for the LRUCache library. I set a max size of 1000. This is a mostly arbitrary limit. Assuming each experiment config is around 100bytes, the cache may grow to roughly 100kb.
[//]: # (Please describe in …
=> Use LRU cache instead of TTL cache

src/eppo-client.spec.ts, src/eppo-client.ts, src/experiment/experiment-configuration.ts, test/mockApiServer.ts
---
---
Customers want to define an allowlist or override such that the same variation is always returned for subjects in the allowlist.
Use the `overrides` field from the RAC response to return variation override.
=> Node SDK - implement allow list

docs/node-server-sdk.iclientconfig.assignmentlogger.md, docs/node-server-sdk.iclientconfig.md, node-server-sdk.api.md, package.json, src/eppo-client.spec.ts, src/eppo-client.ts, src/index.ts
---
---
Fixes Eppo-exp/eppo#3871
Fixes Eppo-exp/eppo#3879
Currently, the experiment has to be enabled for the allow list to work. But the allow list should work regardless of the experiment status or traffic allocation, since it is used for QA.
Do the allow list override check as the first part of the assignment function.
Added unit test
=> Allow assigning subject from overrides when experiment is not enabled

.github/workflows/publish.yml
---
---
Publish GH action fails to run because of nodejs version 12
Just change the version of node to 14+
=> Change node version for publish GH action

src/client/eppo-client.spec.ts, src/client/eppo-client.ts, src/configuration-store.spec.ts, src/configuration-store.ts, src/experiment-configuration-requestor.ts, src/http-client.ts, src/index.ts, src/rule_evaluator.ts, tsconfig.json
---
---
To prep for returning typed values in the node SDK I would like to enable strict null checking.
I am staying with the convention of this repository and returning `null` instead of `undefined`
* enable strict null checks.
* remediate compilation issues.
=> enable strict null checks

node-server-sdk.api.md, package.json, src/index.spec.ts, test/testHelpers.ts, yarn.lock
---
---
Fixes: [FF-898](https://linear.app/eppo/issue/FF-898/node-server)
* Bumps common library version to [v1.5.1](https://github.com/Eppo-exp/js-client-sdk-common/releases/tag/v1.5.1)
* [v1.5.0](https://github.com/Eppo-exp/js-client-sdk-common/releases/tag/v1.5.0) splits `getJSONAssignment` into `getJSONStringAssignment` and `getParsedJSONAssignment`
* [v1.5.1](https://github.com/Eppo-exp/js-client-sdk-common/releases/tag/v1.5.1) has a bug fix that includes `getParsedJSONAssignment` as a property in `IEppoClient`
* Adds tests to support each of the typed assignment methods
[//]: # (Please …
=> Split getJSONAssignment into getJSONStringAssignment and getParsedJSONAssignment by bumping common library version (FF-898)

package.json, src/configuration-store.spec.ts, src/configuration-store.ts
---
---
Fixes: #ff-1990
We need to ensure flags that are no longer in the config are removed when updating the configuration
Clear the configuration store before loading new flags
Added a unit test
=> [UFC] Clear config store before loading new config

node-server-sdk.api.md, package.json, src/index.ts, test/testHelpers.ts, yarn.lock
_Eppo Internal:_
🎟️ **Ticket:** FF-2584 - Export common bandit logger types
Users may want to use the bandit logger types when defining loggers, just as they do with assignment logging
=> Expose bandit logger types

package.json, yarn.lock
_Eppo Internal:_
🎟️ **Ticket:** [FF-2816 - Update Node SDK to use updated Common SDK for no-action bandit calls](https://linear.app/eppo/issue/FF-2816/update-node-sdk-to-use-updated-common-sdk-for-no-action-bandit-calls)
We changed how we handle the situation where no actions are passed to `getBanditAction()`, now always returning the bandit variation if assigned even if no actions are passed (or there was an error selecting an action).
To achieve this, we pull in the latest version of the common SDK where this is supported. See [`js-client-sdk-common #115`](https://github.com/Eppo-exp/js-client-sdk-common/pull/115).
Passes the updated shared bandit test cases (see [`sdk-test-data #46`](https://github.com/Eppo-exp/sdk-test-data/pull/46))
=> Bump common SDK version for updated handling of no-action bandits

package.json, yarn.lock
[js-client-commond-sdk@v4.0.2](https://github.com/Eppo-exp/js-client-sdk-common/releases/tag/v4.0.2)
=> Use latest version of common package

.github/workflows/lint-test-sdk.yml, Makefile
🎟️ Fixes FF-3089 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data#57](https://github.com/Eppo-exp/sdk-test-data/pull/57)
- [php-sdk#38](https://github.com/Eppo-exp/php-sdk/pull/38)
- [dot-net-server-sdk#44](https://github.com/Eppo-exp/dot-net-server-sdk/pull/44)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test …
=> Quality: Parameterize SDK and test-data branches

package.json, src/index.ts, yarn.lock
_Eppo Internal:_
🎟️ **Ticket:** [FF-3144 - Node SDK - Assignment cache should work at the bandit action level](https://linear.app/eppo/issue/FF-3144/node-sdk-assignment-cache-should-work-at-the-bandit-action-level)
👯 **Related PR:** [`js-client-sdk-common #120`](https://github.com/Eppo-exp/js-client-sdk-common/pull/120)
Do not invoke logging callback if the same bandit and action were assigned immediately before
Bump the version of the common SDK so that we can take advantage of this new functionality
Tests in the common SDK
=> Bump version of common js client to take advantage of bandit assignment caching

package.json, yarn.lock
see https://github.com/Eppo-exp/js-client-sdk-common/pull/123 for motivation and context
=> feat: getExperimentContainerEntry helper function for CMS app integration

.github/workflows/lint-test-sdk.yml
Fixes: FF-3646
Testing for in-flight data changes requires running the `lint-and-test.yml` as a reusable workflow within the `sdk-test-data` repository. The checkout action assumes the host repo and target branch for the `repository` and `ref` params, so we need to explicitly set them.
- restore dropped parameters
Reusable testing workflow works.
=> fix: Specify repo and ref in workflow as it is reusable

package.json, yarn.lock
Fixes: #83 
`lru-cache` is an unused dependency. 
`lru-cache` has been removed using `yarn remove`.
This change has not been manually tested as it is not expected to change any functionality.
=> Remove unused lru-cache dependency

package.json, yarn.lock
See https://github.com/Eppo-exp/js-client-sdk/pull/146 for context
Bump js-client-sdk-common to `v4.8.1`
CI
=> chore(deps): Bump common sdk version to match js-client-sdk

package.json, yarn.lock
nodejs precompute must render the `banditKey` as base64, instead of md5.
=> chore: bump commons to 4.8.3-alpha.5

src/i-client-config.ts, src/index.spec.ts, src/index.ts, src/util/index.ts
* Allow disabling event ingestion (false by default)
* Check for read-only file system and use in-memory store if so
* Set default values and forward to underlying factory function
This logic now more closely matches the js-client-sdk implementation https://github.com/Eppo-exp/js-client-sdk/blob/main/src/index.ts#L983-L1004
Wrote tests
=> fix(events): Allow disabling event logging, check r/o FS

node-server-sdk.api.md, package.json, src/index.ts, yarn.lock
* Bump js-common-sdk to v4.13.0
* Export new API `EppoAssignmentLogger`
As above
=> chore: Prepare for v3.9.0 release

package.json, src/i-client-config.ts, src/index.spec.ts, src/index.ts
:tickets: Fixes __issue__
:scroll: Design Doc: __link if applicable__
[//]: # (Please describe how you documented the developer impact of your changes; link to PRs or issues or explain why no documentation changes are required)
=> [FFL-648] allowed pollAfterSuccessfulInitialization to be configurable
